version: "3.9"

networks:
  pvh_net:
    driver: bridge

services:
    compare:
      build:
        context: ./compare
        dockerfile: Dockerfile
      container_name: "compare"
      restart: on-failure
      ports:
        - 8800:8800
      networks:
        - pvh_net
      command: go run ./cmd/api/.