version: "3.9"

networks:
  pvh_net:
    driver: bridge

services:
    notifications:
      build:
        context: ./compare
        dockerfile: Dockerfile
      container_name: "compare"
      restart: on-failure
      ports:
        - 80:8800
      networks:
        - pvh_net
      command: go run main.go