definitions:
  Error:
    properties:
      msg:
        type: string
        x-go-name: Msg
    type: object
    x-go-name: ApiError
    x-go-package: compare/api_error
  ListTask:
    items:
      $ref: '#/definitions/Task'
    type: array
    x-go-package: compare/models/task
  NewTask:
    properties:
      id_compare:
        format: int64
        type: integer
        x-go-name: IdTask
      id_users:
        format: int64
        type: integer
        x-go-name: IdUser
      summary:
        type: string
        x-go-name: Summary
    type: object
    x-go-package: compare/models/task
  NewTaskRequestBody:
    properties:
      summary:
        description: in:body
        minimum: 1
        type: string
        x-go-name: Summary
    required:
    - summary
    type: object
    x-go-package: compare/controllers/task
  Task:
    properties:
      created_at:
        type: string
        x-go-name: CreatedAt
      id:
        format: int64
        type: integer
        x-go-name: Id
      summary:
        type: string
        x-go-name: Summary
      user:
        type: string
        x-go-name: User
    type: object
    x-go-package: compare/models/task
info: {}
paths:
  /task:
    get:
      description: 'Description: If manager lists all task if technician only list
        the compare that are created by the authenticated user'
      operationId: get_list_compare
      produces:
      - application/json
      responses:
        "200":
          description: ListTask
          schema:
            $ref: '#/definitions/ListTask'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/Error'
      schemes:
      - https
      security:
      - BasicAuth: []
      summary: Gets List of compare.
      tags:
      - get_list_compare
    post:
      consumes:
      - application/json
      description: 'Description: Create New Task'
      operationId: NewTaskRequest
      parameters:
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/NewTaskRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: NewTask
          schema:
            $ref: '#/definitions/NewTask'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/Error'
      schemes:
      - https
      security:
      - BasicAuth: []
      summary: Create New Task.
      tags:
      - new_task
  /task/{id}:
    get:
      description: 'Description: Gets one task'
      operationId: GetOneRequest
      parameters:
      - format: int64
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
        x-go-name: Id
      produces:
      - application/json
      responses:
        "200":
          description: Task
          schema:
            $ref: '#/definitions/Task'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/Error'
      schemes:
      - https
      security:
      - BasicAuth: []
      summary: Gets one task.
      tags:
      - get_one_task
  /users/{id}/task:
    get:
      description: 'Description: Get lists of compare by user only for managers'
      operationId: GetByUserRequest
      parameters:
      - format: int64
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
        x-go-name: Id
      produces:
      - application/json
      responses:
        "200":
          description: ListTask
          schema:
            $ref: '#/definitions/ListTask'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/Error'
      schemes:
      - https
      security:
      - BasicAuth: []
      summary: Gets List of compare By user.
      tags:
      - get_list_compare_by_user
swagger: "2.0"
